### ISSUE TITLE
Roadmap to 1.0.0-beta

### ISSUE THREAD

**Issue by shishome** [shishome/fractal#1]
- [x] Working Lines Manager
- [x] Add/remove images, gifs #3 
- [ ] mp4s as repeatable files (optional) 
- [x] save/load functionality #4 
- [x] versioning inside the save/load files (v1.0 should break in v2.0) #5 
- [ ] audio soundtrack option
- [x] Relative pathing for files (maybe, depends on how file pathing plays out)
- [ ] speed control for text/images/animations
- [ ] multiple different animation types
- [ ] record screen to MP4 file #6 
- [ ] helptext for sprial control
- [ ] timer functionality for sessions (default to endless)
- [ ] "subprogram" system (see this issue: #2) (this may be moved to 2.x due to how it'll need to be saved)
- [ ] Auto-update the program using autoupdater #12 

Next Milestone Roadmap: (Coming Soon)

**Comment by shishome** [comment]
Removed save-as functionality in cb6f8c0d92c0138c8b0daf0a74fc6f849e4ecd9d because the new way I'm saving files doesn't really work well with that paradigm.
